# Generated by Django 4.2 on 2025-06-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="assignedarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_id", models.CharField(max_length=100)),
                ("area_name", models.CharField(max_length=100)),
                ("worker_id", models.CharField(max_length=100)),
                ("from_date", models.CharField(max_length=50)),
                ("till_date", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="childInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("child_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("age", models.CharField(max_length=50)),
                ("parent_contact", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=100)),
                ("vaccine_status", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="citizen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("citizen_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("contact_no", models.IntegerField()),
                ("city", models.CharField(max_length=50)),
                ("mail", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hosp_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("contact", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vaccination", models.CharField(max_length=100)),
                ("start_end_date", models.CharField(max_length=50)),
                ("start_end_time", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("contact_no", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_id", models.CharField(max_length=100)),
                ("vaccine_name", models.CharField(max_length=100)),
                ("quantity", models.CharField(max_length=50)),
                ("last_updated", models.CharField(max_length=50)),
                ("hosp_id", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="UserLogin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=100)),
                ("user_type", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="vaccinationdetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_id", models.CharField(max_length=100)),
                ("vaccine_name", models.CharField(max_length=100)),
                ("dose_num", models.CharField(max_length=50)),
                ("vaccination_date", models.CharField(max_length=50)),
                ("given_by", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="vaccinationrequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.CharField(max_length=100)),
                ("citizen_id", models.CharField(max_length=100)),
                ("citizen_name", models.CharField(max_length=100)),
                ("requested_date", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="vaccinecollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection_id", models.CharField(max_length=100)),
                ("worker_id", models.CharField(max_length=100)),
                ("vaccine_name", models.CharField(max_length=100)),
                ("hosp_id", models.CharField(max_length=100)),
                ("quantity", models.CharField(max_length=50)),
                ("collection_date", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("worker_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("experience", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("mobile_no", models.CharField(max_length=50)),
                ("gender", models.CharField(max_length=50)),
                ("hosp_id", models.CharField(max_length=100)),
            ],
        ),
    ]
