# Generated by Django 4.2 on 2025-06-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("citizens", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="dosagedetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dose_id", models.CharField(max_length=100)),
                ("citizen_id", models.CharField(max_length=100)),
                ("vaccine_name", models.CharField(max_length=100)),
                ("dose_num", models.CharField(max_length=50)),
                ("vaccination_date", models.CharField(max_length=50)),
                ("given_by", models.CharField(max_length=100)),
            ],
        ),
    ]
